### ISSUE TITLE
Costum shortcode with css not renderd in hugo production mode

### ISSUE THREAD

**Issue by winux1** [gethugothemes/navigator-hugo#45]
Hello!
I am using the navigator theme for hugo. I managed to create a costum shortcode with css. When I am running the hugo server command it renders nicely but when I use the hugo command it only renders pure text.
Here is my code and css:
The code:
```html
<div class="shortcode-notice {{ .Get 0 }}">
<div class="shortcode-notice-title {{ .Get 0 }}">
{{- if len .Params | eq 2 -}}
{{ .Get 1 }}
{{ else }}
{{ .Get 0 }}
{{- end -}}
</div>
<div class="notice-content">{{ .Inner | markdownify }}</div>
</div>
```

The css:
```css
/*=================================================================
Notice Shortcode
==================================================================*/
.shortcode-notice .notice-content {
padding: 0.6em 1em;
display: block;
font-size: 1em;
margin-top: 0;
margin-bottom: 0;
color: #666;
}
.shortcode-notice-title {
color: #fff;
padding-left: 1em;
font-weight: bold;
}
.shortcode-notice-title.note {
background-color: #6ab0de;
}
.shortcode-notice.note .notice-content {
background: #e7f2fa;
}
.shortcode-notice-title.tip {
background-color: rgba(92, 184, 92, 0.8);
}
.shortcode-notice.tip .notice-content {
background: #e6f9e6;
}
.shortcode-notice-title.info {
background-color: #f0b37e;
}
.shortcode-notice.info .notice-content {
background: #fff2db;
}
.shortcode-notice-title.warning {
background-color: rgba(217, 83, 79, 0.8);
}
.shortcode-notice.warning .notice-content {
background: #fae2e2;
}
```

How can I make it work?
Thanks for your help in advance!
